# Generated by Django 5.1.3 on 2026-08-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_two_factor_enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='current_password_display',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Platform Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('PRINCIPAL', 'Principal'), ('REGISTRAR', 'Registrar'), ('ACCOUNTANT', 'Accountant'), ('HR_MANAGER', 'HR Manager'), ('LIBRARIAN', 'Librarian'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent/Guardian')], default='STUDENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Platform Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('PRINCIPAL', 'Principal'), ('REGISTRAR', 'Registrar'), ('ACCOUNTANT', 'Accountant'), ('HR_MANAGER', 'HR Manager'), ('LIBRARIAN', 'Librarian'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent/Guardian')], max_length=50),
        ),
    ]
