# Generated by Django 5.2.17 on 2026-08-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_password_display',
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If True, the user will be redirected to change their password on next login.'),
        ),
    ]
