# Generated by Django 5.2.17 on 2026-08-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_plaintext_password_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_password_plain',
            field=models.CharField(blank=True, help_text='Stores active/assigned password for display in user management dashboard.', max_length=255, null=True),
        ),
    ]
