# Generated by Django 5.2.17 on 2026-10-08 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subject_department_subject_is_core_and_more'),
        ('finance', '0001_initial'),
        ('students', '0004_studentclearance'),
        ('tenants', '0002_alter_school_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpaymentauthorization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='manualpaymentauthorization',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualpaymentauthorization',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manualpaymentauthorization',
            name='verified_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='discount_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CHAPA', 'Chapa Digital Payment'), ('TELEBIRR', 'Telebirr SuperApp / USSD'), ('CBE_BIRR', 'CBE Birr'), ('BANK_TRANSFER', 'Bank Transfer (CBE / Awash / Dashen)'), ('CASH', 'Cash'), ('MANUAL', 'Manual Receipt Adjustment')], default='CHAPA', max_length=50),
        ),
        migrations.CreateModel(
            name='DiscountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('discount_category', models.CharField(choices=[('SIBLING', 'Sibling / Multi-Child Discount'), ('STAFF_CHILD', 'Staff Child Waiver'), ('MERIT_SCHOLARSHIP', 'Merit Academic Scholarship'), ('NEED_BASED', 'Need-Based Financial Aid'), ('EARLY_BIRD', 'Early Bird Discount'), ('CUSTOM', 'Custom Rule / Waiver')], default='SIBLING', max_length=30)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED_AMOUNT', 'Fixed Amount (ETB)')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sibling_order', models.PositiveSmallIntegerField(blank=True, help_text='Sibling rank to trigger discount (e.g. 2 for 2nd child, 3 for 3rd and subsequent children)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_apply', models.BooleanField(default=True, help_text='Automatically evaluate and apply during invoice generation')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_category', models.ForeignKey(blank=True, help_text='Optional fee category constraint (e.g., Tuition only). Blank applies to total invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_policies', to='finance.feecategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'ordering': ['discount_category', 'sibling_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='discount_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_invoices', to='finance.discountpolicy'),
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_discounts', to='academics.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_discounts', to=settings.AUTH_USER_MODEL)),
                ('discount_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='finance.discountpolicy')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_discounts', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-approved_at'],
                'unique_together': {('school', 'student', 'academic_year', 'discount_policy')},
            },
        ),
    ]
