# Generated by Django 5.1.15 on 2026-08-11 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=45)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('FULL_DAY', 'Full Day')], default='FULL_DAY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('GEN', 'General'), ('NAT', 'Natural Science'), ('SOC', 'Social Science')], default='GEN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StreamCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_overall_average', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('subject_requirements', models.JSONField(default=dict, help_text="Minimum marks dictionary e.g. {'MATH': 75.0, 'PHYS': 70.0}")),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('amharic_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday / ሰኞ'), ('TUESDAY', 'Tuesday / ማክሰኞ'), ('WEDNESDAY', 'Wednesday / ረቡዕ'), ('THURSDAY', 'Thursday / ሐሙስ'), ('FRIDAY', 'Friday / አርብ')], max_length=20)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ethiopian_year', models.IntegerField(default=2016)),
                ('gregorian_start_date', models.DateField()),
                ('gregorian_end_date', models.DateField()),
                ('ethiopian_start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('ethiopian_end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('CLOSING', 'Closing'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('SEMESTER', 'Semester'), ('TERM', 'Term'), ('QUARTER', 'Quarter'), ('CUSTOM', 'Custom')], default='SEMESTER', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_periods', to='academics.academicyear')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('SCHOOL_EVENT', 'School Event'), ('PARENT_MEETING', 'Parent Meeting'), ('TEACHER_MEETING', 'Teacher Meeting'), ('HOLIDAY', 'Holiday'), ('CEREMONY', 'School Ceremony / Celebration'), ('EXAM_PERIOD', 'Examination Period'), ('REGISTRATION_PERIOD', 'Registration Period'), ('RESULT_PUBLICATION', 'Result Publication Date'), ('YEAR_CLOSING', 'Year Closing')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='academics.academicyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('stream_type', models.CharField(choices=[('GEN', 'General'), ('NAT', 'Natural Science'), ('SOC', 'Social Science')], default='GEN', max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'ordering': ['level', 'stream_type'],
            },
        ),
        migrations.CreateModel(
            name='PeriodSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift', models.CharField(default='FULL_DAY', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='PromotionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Promotion Policy', max_length=100)),
                ('minimum_average', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('minimum_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, max_digits=5)),
                ('maximum_failed_subjects', models.IntegerField(default=2)),
                ('allow_conditional_promotion', models.BooleanField(default=True)),
                ('allow_supplementary_exam', models.BooleanField(default=True)),
                ('graduation_minimum_gpa', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_policies', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('SCHOOL_EVENT', 'School Event'), ('PARENT_MEETING', 'Parent Meeting'), ('TEACHER_MEETING', 'Teacher Meeting'), ('HOLIDAY', 'Holiday'), ('CEREMONY', 'School Ceremony / Celebration'), ('EXAM_PERIOD', 'Examination Period'), ('REGISTRATION_PERIOD', 'Registration Period'), ('RESULT_PUBLICATION', 'Result Publication Date'), ('YEAR_CLOSING', 'Year Closing')], default='SCHOOL_EVENT', max_length=50)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('PARENTS', 'Parents'), ('TEACHERS', 'Teachers'), ('STUDENTS', 'Students')], default='ALL', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_events', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
