# Generated by Django 5.1.15 on 2026-08-11 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='stream',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.stream'),
        ),
        migrations.AddField(
            model_name='streamcriteria',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_criteria', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='streamcriteria',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='streamcriteria',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='academics.stream'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.stream'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='period_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.periodslot'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.section'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='teachers.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='academicperiod',
            unique_together={('school', 'academic_year', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('school', 'level', 'stream_type')},
        ),
        migrations.AlterUniqueTogether(
            name='periodslot',
            unique_together={('school', 'name', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='promotionpolicy',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('school', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('school', 'grade', 'stream', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='streamcriteria',
            unique_together={('school', 'stream', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code', 'grade', 'stream')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('school', 'section', 'day_of_week', 'period_slot')},
        ),
    ]
