# Generated by Django 5.1.15 on 2026-08-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperiod',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked')], default='OPEN', max_length=20),
        ),
    ]
