# Generated by Django 5.1.3 on 2026-08-15 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicperiod_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tutorial_teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher assigned as Tutorial Controller for this section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
