# Generated by Django 5.2.17 on 2026-10-07 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_section_tutorial_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolevent',
            options={'ordering': ['start_date', 'start_time']},
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='academic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='academics.academicperiod'),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='event_category',
            field=models.CharField(choices=[('ACADEMIC', 'Academic Calendar & Terms'), ('EXAMINATION', 'Examinations & Assessments'), ('HOLIDAY', 'National & Religious Holidays'), ('BREAK', 'School Breaks & Vacations'), ('REGISTRATION', 'Registration & Admission'), ('TRAINING', 'Teacher Training & Workshops'), ('MEETING', 'Parent-Teacher & Staff Meetings'), ('CEREMONY', 'School Events & Ceremonies'), ('EXTRACURRICULAR', 'Sports & Extracurricular'), ('OTHER', 'Other')], default='ACADEMIC', max_length=30),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='is_automated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='is_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolevent',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=20),
        ),
    ]
