# Generated by Django 5.2.17 on 2026-10-07 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_schoolevent_options_and_more'),
        ('tenants', '0002_alter_school_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperiod',
            name='has_supplementary_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='instructional_days',
            field=models.PositiveIntegerField(default=90, help_text='Planned instruction days in this semester/term'),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='reopen_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='supplementary_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='supplementary_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicperiod',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='SemesterArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('passed_students', models.PositiveIntegerField(default=0)),
                ('failed_students', models.PositiveIntegerField(default=0)),
                ('overall_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('snapshot_data', models.JSONField(default=dict, help_text='Summary metrics, pass rates, and grade averages at time of archiving')),
                ('notes', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_archives', to='academics.academicyear')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_semester_archives', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='academics.academicperiod')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'ordering': ['-archived_at'],
            },
        ),
    ]
