# Generated by Django 5.2.17 on 2026-10-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_academicperiod_has_supplementary_exam_and_more'),
        ('teachers', '0002_teacherprofile_max_daily_periods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='teachers.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_core',
            field=models.BooleanField(default=False, help_text='Core academic subjects (Maths, English, Sciences) prioritized for morning slots'),
        ),
        migrations.AddField(
            model_name='subject',
            name='preferred_room_type',
            field=models.CharField(choices=[('CLASSROOM', 'General Classroom'), ('SCIENCE_LAB', 'Science Laboratory'), ('COMPUTER_LAB', 'Computer Laboratory'), ('SPORTS_FIELD', 'Sports Field / Gymnasium')], default='CLASSROOM', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='weekly_periods',
            field=models.PositiveIntegerField(default=4, help_text='Standard weekly periods for this subject in the curriculum (e.g. 5 for Math/English, 4 for Sciences, 2 for PE)'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked slots are pinned and protected from automated timetable regeneration'),
        ),
    ]
