# Generated by Django 5.1.3 on 2026-08-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_password_display',
            field=models.CharField(blank=True, default='student123', max_length=128, null=True),
        ),
    ]
