# Generated by Django 5.2.17 on 2026-08-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_current_password_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_password_display',
        ),
    ]
