# Generated by Django 5.2.17 on 2026-10-08 16:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subject_department_subject_is_core_and_more'),
        ('enrollment', '0002_alter_studentenrollment_options'),
        ('students', '0003_remove_plaintext_password_storage'),
        ('tenants', '0002_alter_school_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearance_number', models.CharField(max_length=50)),
                ('withdrawal_reason', models.CharField(choices=[('TRANSFER', 'Transfer to Another School'), ('RELOCATION', 'Family Relocation / Moving'), ('FINANCIAL', 'Financial Reasons'), ('MEDICAL', 'Health / Medical Reasons'), ('GRADUATION', 'Graduation / Completed Studies'), ('PERSONAL', 'Personal / Family Reasons'), ('DISCIPLINARY', 'Disciplinary Expulsion'), ('OTHER', 'Other')], default='TRANSFER', max_length=30)),
                ('reason_details', models.TextField(blank=True, null=True)),
                ('destination_school', models.CharField(blank=True, help_text='Destination school transferred to', max_length=200, null=True)),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated (Pending Clearances)'), ('UNDER_REVIEW', 'Under Department Review'), ('APPROVED', 'Fully Cleared & Approved'), ('REJECTED', 'Clearance Rejected / Blocked'), ('WITHDRAWN', 'Official Withdrawal Finalized')], default='INITIATED', max_length=30)),
                ('library_cleared', models.BooleanField(default=False)),
                ('library_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('library_remarks', models.TextField(blank=True, null=True)),
                ('finance_cleared', models.BooleanField(default=False)),
                ('finance_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('finance_remarks', models.TextField(blank=True, null=True)),
                ('academic_cleared', models.BooleanField(default=False)),
                ('academic_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('academic_remarks', models.TextField(blank=True, null=True)),
                ('property_cleared', models.BooleanField(default=False)),
                ('property_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('property_remarks', models.TextField(blank=True, null=True)),
                ('final_approved_at', models.DateTimeField(blank=True, null=True)),
                ('final_remarks', models.TextField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_academic_clearances', to=settings.AUTH_USER_MODEL)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_clearances', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearances', to='enrollment.studentenrollment')),
                ('final_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_final_clearances', to=settings.AUTH_USER_MODEL)),
                ('finance_cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_finance_clearances', to=settings.AUTH_USER_MODEL)),
                ('library_cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_library_clearances', to=settings.AUTH_USER_MODEL)),
                ('property_cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_property_clearances', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('school', 'clearance_number')},
            },
        ),
    ]
