# Generated by Django 5.1.15 on 2026-08-11 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('section_rank', models.IntegerField()),
                ('stream_rank', models.IntegerField()),
                ('grade_rank', models.IntegerField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.grade')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicperiod')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'ordering': ['section_rank'],
                'unique_together': {('school', 'academic_year', 'period', 'student')},
            },
        ),
    ]
