# Generated by Django 5.1.3 on 2026-08-13 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicperiod_status'),
        ('assessments', '0001_initial'),
        ('enrollment', '0001_initial'),
        ('tenants', '0002_alter_school_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperiodresult',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='academicperiodresult',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='AnnualResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('section_rank', models.IntegerField(blank=True, null=True)),
                ('grade_rank', models.IntegerField(blank=True, null=True)),
                ('promotion_status', models.CharField(choices=[('PROMOTED', 'Promoted'), ('REPEATED', 'Repeated'), ('PENDING_REVIEW', 'Pending Review (Caution)')], default='PENDING_REVIEW', max_length=20)),
                ('results_json', models.JSONField(default=dict, help_text='Detailed per-subject annual results cache')),
                ('is_locked', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_results_agg', to='academics.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_results', to='enrollment.studentenrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'unique_together': {('school', 'enrollment', 'academic_year')},
            },
        ),
    ]
