# Generated by Django 5.1.3 on 2026-08-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_academicperiodresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperiodresult',
            name='attendance_absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academicperiodresult',
            name='attendance_late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academicperiodresult',
            name='attendance_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annualresult',
            name='attendance_absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annualresult',
            name='attendance_late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annualresult',
            name='attendance_present',
            field=models.IntegerField(default=0),
        ),
    ]
