# Generated by Django 5.2.17 on 2026-08-15 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_academicperiodresult_attendance_absent_and_more'),
        ('enrollment', '0002_alter_studentenrollment_options'),
        ('tenants', '0002_alter_school_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['school', 'status'], name='assessments_school__444765_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmark',
            index=models.Index(fields=['school', 'enrollment', 'status'], name='assessments_school__83c02a_idx'),
        ),
    ]
