# Generated by Django 5.2.17 on 2026-10-08 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_academicperiod_has_supplementary_exam_and_more'),
        ('assessments', '0005_markentrylock'),
        ('enrollment', '0002_alter_studentenrollment_options'),
        ('students', '0003_remove_plaintext_password_storage'),
        ('tenants', '0002_alter_school_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcomponent',
            name='assessment_type',
            field=models.CharField(choices=[('NUMERICAL', 'Numerical / Percentage'), ('LETTER_GRADE', 'Letter / Grade')], default='NUMERICAL', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentcomponent',
            name='min_passing_mark',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='markentrylock',
            name='assessment_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_entry_locks', to='assessments.assessmentcomponent'),
        ),
        migrations.AddField(
            model_name='markentrylock',
            name='unlock_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='markentrylock',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='markentrylock',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_mark_locks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='grade_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='markentrylock',
            name='lock_type',
            field=models.CharField(choices=[('GRADE', 'By Grade'), ('SUBJECT', 'By Subject'), ('TEACHER', 'By Teacher'), ('SECTION', 'By Section'), ('COMPONENT', 'By Assessment Component'), ('CUSTOM', 'Custom / Targeted')], default='CUSTOM', max_length=20),
        ),
        migrations.CreateModel(
            name='AcademicIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_score', models.DecimalField(decimal_places=2, help_text='Score that triggered the intervention (<60%)', max_digits=5)),
                ('threshold_applied', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('intervention_type', models.CharField(choices=[('TUTORIAL', 'Tutorial / Remedial Class'), ('PARENT_MEETING', 'Parent Conference / Meeting'), ('COUNSELING', 'Academic Counseling'), ('PEER_TUTORING', 'Peer Tutoring'), ('BEHAVIOR_CONTRACT', 'Study Plan Contract'), ('CUSTOM', 'Custom Intervention')], default='TUTORIAL', max_length=30)),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified (Pending Action)'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved (Performance Improved)'), ('ESCALATED', 'Escalated to Administration'), ('CLOSED', 'Closed')], default='IDENTIFIED', max_length=30)),
                ('action_plan', models.TextField(help_text='Prescribed remediation plan, remedial topics, or meeting agenda')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notified_at', models.DateTimeField(blank=True, null=True)),
                ('parent_notification_channel', models.CharField(choices=[('SMS', 'SMS'), ('PORTAL', 'In-App Portal'), ('PHONE', 'Phone Call'), ('IN_PERSON', 'In Person')], default='SMS', max_length=20)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_score', models.DecimalField(blank=True, decimal_places=2, help_text='Retest / reassessment mark', max_digits=5, null=True)),
                ('outcome_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='academics.academicyear')),
                ('assessment_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='assessments.assessmentcomponent')),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interventions', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='enrollment.studentenrollment')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='academics.academicperiod')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_interventions', to='students.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scale_type', models.CharField(choices=[('NUMERICAL', 'Numerical / Percentage'), ('LETTER_GRADE', 'Letter / Grade')], default='NUMERICAL', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('min_passing_mark', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('below_average_threshold', models.DecimalField(decimal_places=2, default=60.0, help_text='Threshold below which score is highlighted in red and flagged for intervention', max_digits=5)),
                ('high_performance_threshold', models.DecimalField(decimal_places=2, default=90.0, help_text='Threshold at or above which score is highlighted as high performance', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(blank=True, help_text='Specific grade level (leave blank for school default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_scales', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GradingScaleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_grade', models.CharField(max_length=10)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa_point', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_passing', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='assessments.gradingscale')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'ordering': ['-min_score'],
            },
        ),
    ]
