# Generated by Django 5.1.15 on 2026-08-11 21:37

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ADMISSION_DOC', 'Student Admission Document'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('TEACHER_CREDENTIAL', 'Teacher Qualification Credential'), ('STUDENT_TRANSCRIPT', 'Official Transcript'), ('OTHER', 'Other School Document')], default='OTHER', max_length=50)),
                ('file', models.FileField(upload_to='school_documents/', validators=[apps.documents.models.validate_file_extension_and_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.studentprofile')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teachers.teacherprofile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
