# Generated by Django 5.1.15 on 2026-08-11 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.SlugField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('woreda', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='school_stamps/')),
                ('calendar_preference', models.CharField(choices=[('ETHIOPIAN', 'Ethiopian Calendar'), ('GREGORIAN', 'Gregorian Calendar')], default='ETHIOPIAN', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_SETUP', 'Pending Setup'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING_SETUP', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.school')),
            ],
        ),
    ]
