# Generated by Django 5.1.3 on 2026-08-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('PENDING_SETUP', 'Pending Setup'), ('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='PENDING_SETUP', max_length=20),
        ),
    ]
