# Generated by Django 5.1.15 on 2026-08-11 21:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('BASIC', 'Basic (Up to 500 Students)'), ('STANDARD', 'Standard (Up to 1,500 Students)'), ('PREMIUM', 'Premium (Unlimited/Enterprise)')], default='BASIC', max_length=20, unique=True)),
                ('max_students', models.IntegerField(default=500)),
                ('max_teachers', models.IntegerField(default=30)),
                ('max_sms_per_month', models.IntegerField(default=1000)),
                ('max_storage_mb', models.IntegerField(default=5000)),
                ('price_per_year_etb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Trial Period'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('GRACE_PERIOD', 'Grace Period'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=20)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('grace_period_end_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.school')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='TenantUsageMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_students_count', models.IntegerField(default=0)),
                ('current_teachers_count', models.IntegerField(default=0)),
                ('sms_sent_this_month', models.IntegerField(default=0)),
                ('storage_used_mb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_reset_date', models.DateField(default=datetime.date.today)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
