# Generated by Django 5.1.3 on 2026-08-13 20:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsubscription',
            name='base_fee_etb',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='custom_annual_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='max_staff_limit',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='max_students_limit',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='price_per_staff_etb',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='price_per_student_etb',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='schoolsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan'),
        ),
    ]
