# Generated by Django 5.2.17 on 2026-08-20 10:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_section_tutorial_teacher'),
        ('tenants', '0002_alter_school_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('meeting_type', models.CharField(choices=[('VIRTUAL_CLASS', 'Virtual Class / Live Lecture'), ('PARENT_TEACHER', 'Parent-Teacher Conference'), ('STAFF_MEETING', 'Staff / Department Meeting'), ('DIRECT_CALL', 'Direct 1-on-1 Consultation'), ('GENERAL', 'General Meeting / Assembly')], default='VIRTUAL_CLASS', max_length=30)),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('passcode', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduled_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live Now'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_meetings', to='academics.academicyear')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_video_meetings', to=settings.AUTH_USER_MODEL)),
                ('invited_participants', models.ManyToManyField(blank=True, related_name='invited_video_meetings', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('target_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_meetings', to='academics.grade')),
                ('target_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_meetings', to='academics.section')),
                ('target_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_meetings', to='academics.subject')),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_present', models.BooleanField(default=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='video_calls.videomeeting')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videomeeting',
            index=models.Index(fields=['school', 'status', 'scheduled_start'], name='video_calls_school__743c35_idx'),
        ),
        migrations.AddIndex(
            model_name='videomeeting',
            index=models.Index(fields=['school', 'meeting_type'], name='video_calls_school__83b58f_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['meeting', 'user'], name='video_calls_meeting_60677a_idx'),
        ),
    ]
