# Generated by Django 5.2.17 on 2026-08-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_section_tutorial_teacher'),
        ('tenants', '0002_alter_school_status'),
        ('video_calls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingattendance',
            name='guest_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videomeeting',
            name='allow_guest_access',
            field=models.BooleanField(default=True, help_text='Allow external guests to join without logging in using a secure guest link'),
        ),
        migrations.AddField(
            model_name='videomeeting',
            name='guest_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videomeeting',
            name='meeting_type',
            field=models.CharField(choices=[('VIRTUAL_CLASS', 'Virtual Class / Live Lecture'), ('PARENT_TEACHER', 'Parent-Teacher Conference'), ('STAFF_MEETING', 'Staff / Department Meeting'), ('DIRECT_CALL', 'Direct 1-on-1 Consultation'), ('GUEST_CONSULTATION', 'Special Guest / VIP & External Call'), ('GENERAL', 'General Meeting / Assembly')], default='VIRTUAL_CLASS', max_length=30),
        ),
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['meeting', 'is_guest'], name='video_calls_meeting_d638f3_idx'),
        ),
        migrations.AddIndex(
            model_name='videomeeting',
            index=models.Index(fields=['guest_token'], name='video_calls_guest_t_a7552f_idx'),
        ),
    ]
