# Generated by Django 5.1.15 on 2026-08-11 21:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_changes_from', to='academics.stream')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_changes', to='students.studentprofile')),
                ('to_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_changes_to', to='academics.stream')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('enrollment_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROMOTED', 'Promoted'), ('PROMOTED_WITH_CONDITIONS', 'Promoted with Conditions'), ('RETAINED', 'Retained (Repeating Grade)'), ('SPECIAL_REVIEW', 'Special Review'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred Out'), ('WITHDRAWN', 'Withdrawn'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=30)),
                ('admission_type', models.CharField(choices=[('NEW', 'New Admission'), ('TRANSFER', 'Transfer In'), ('READMISSION', 'Readmission')], default='NEW', max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.section')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('school', 'academic_year', 'student')},
            },
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='students.studentprofile')),
                ('from_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_from', to='enrollment.studentenrollment')),
                ('to_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_to', to='enrollment.studentenrollment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('INTERNAL', 'Internal Section Transfer'), ('EXTERNAL', 'External School Transfer')], default='INTERNAL', max_length=20)),
                ('reason', models.TextField()),
                ('destination_school', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='academics.section')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='students.studentprofile')),
                ('to_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='academics.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('library_cleared', models.BooleanField(default=False)),
                ('finance_cleared', models.BooleanField(default=False)),
                ('property_cleared', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='enrollment.studentenrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='students.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentPromotionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('failed_subjects_count', models.IntegerField(default=0)),
                ('failed_subjects_json', models.JSONField(default=list)),
                ('section_rank', models.IntegerField(blank=True, null=True)),
                ('grade_rank', models.IntegerField(blank=True, null=True)),
                ('system_recommendation', models.CharField(choices=[('PROMOTED', 'Promoted'), ('PROMOTED_WITH_CONDITIONS', 'Promoted with Conditions'), ('RETAINED', 'Retained (Repeating Grade)'), ('SPECIAL_REVIEW', 'Special Administrative Review'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred Out'), ('WITHDRAWN', 'Withdrawn')], max_length=30)),
                ('admin_decision', models.CharField(blank=True, choices=[('PROMOTED', 'Promoted'), ('PROMOTED_WITH_CONDITIONS', 'Promoted with Conditions'), ('RETAINED', 'Retained (Repeating Grade)'), ('SPECIAL_REVIEW', 'Special Administrative Review'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred Out'), ('WITHDRAWN', 'Withdrawn')], max_length=30, null=True)),
                ('conditions_notes', models.TextField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_decisions', to='academics.academicyear')),
                ('allocated_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_promotion_decisions', to='academics.grade')),
                ('allocated_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_promotion_decisions', to='academics.section')),
                ('allocated_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_promotion_decisions', to='academics.stream')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_decision', to='enrollment.studentenrollment')),
                ('policy_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.promotionpolicy')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'unique_together': {('school', 'enrollment')},
            },
        ),
        migrations.CreateModel(
            name='StudentStreamPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_preferences', to='academics.academicyear')),
                ('preference_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref1_students', to='academics.stream')),
                ('preference_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pref2_students', to='academics.stream')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_preferences', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('school', 'student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='enrollment.studentenrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('school', 'enrollment', 'subject')},
            },
        ),
    ]
