# Generated by Django 5.1.3 on 2026-08-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ['-academic_year__gregorian_start_date', '-grade__level', '-id']},
        ),
    ]
