# Generated by Django 5.1.15 on 2026-08-11 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('MISCONDUCT', 'Misconduct / Disruptive Behaviour'), ('BULLYING', 'Bullying / Harassment'), ('FIGHTING', 'Physical Altercation / Fighting'), ('CHEATING', 'Academic Dishonesty / Cheating'), ('DAMAGE', 'Property Damage'), ('ABSENCE', 'Unauthorized Absence / Truancy'), ('DRESS_CODE', 'Dress Code Violation'), ('SUBSTANCE', 'Substance Use'), ('WEAPONS', 'Weapons / Dangerous Items'), ('OTHER', 'Other')], default='MISCONDUCT', max_length=30)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SERIOUS', 'Serious'), ('CRITICAL', 'Critical')], default='MINOR', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open / Under Review'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated to Principal'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('description', models.TextField()),
                ('incident_date', models.DateField()),
                ('location', models.CharField(blank=True, help_text='e.g. Classroom, Corridor, Canteen', max_length=100, null=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notification_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='academics.academicyear')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_incidents', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('students_involved', models.ManyToManyField(blank=True, related_name='disciplinary_incidents', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('VERBAL_WARNING', 'Verbal Warning'), ('WRITTEN_WARNING', 'Written Warning'), ('DETENTION', 'Detention'), ('PARENT_CALL', 'Parent Notified / Called'), ('SUSPENSION', 'Suspension (Days)'), ('COMMUNITY_SERVICE', 'Community Service'), ('EXPULSION', 'Expulsion Recommended'), ('OTHER', 'Other Action')], default='VERBAL_WARNING', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('suspension_days', models.IntegerField(default=0, help_text='Number of suspension days (if applicable)')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='students.studentprofile')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='discipline.disciplinaryincident')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
