# Generated by Django 5.1.3 on 2026-08-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Platform Super Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('PRINCIPAL', 'Principal'), ('REGISTRAR', 'Registrar'), ('ACCOUNTANT', 'Accountant'), ('HR_MANAGER', 'HR Manager'), ('LIBRARIAN', 'Librarian'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent/Guardian')], max_length=50, null=True),
        ),
    ]
