# Generated by Django 5.2.17 on 2026-08-15 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_section_tutorial_teacher'),
        ('attendance', '0002_tutorialattendancerecord'),
        ('students', '0002_studentprofile_current_password_display'),
        ('tenants', '0002_alter_school_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'date'], name='attendance__school__8edf1d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'section', 'date'], name='attendance__school__94ac76_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['school', 'student', 'status'], name='attendance__school__b0e088_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorialattendancerecord',
            index=models.Index(fields=['school', 'date'], name='attendance__school__9890b5_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorialattendancerecord',
            index=models.Index(fields=['school', 'section', 'date'], name='attendance__school__6db145_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorialattendancerecord',
            index=models.Index(fields=['school', 'student', 'status'], name='attendance__school__4bff1d_idx'),
        ),
    ]
