# Generated by Django 5.2.17 on 2026-10-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('tenants', '0002_alter_school_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='max_daily_periods',
            field=models.PositiveIntegerField(default=6, help_text='Maximum allowed teaching periods per single day'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='max_weekly_periods',
            field=models.PositiveIntegerField(default=25, help_text='Maximum allowed teaching periods per week (Standard Ethiopian curriculum: 20-30)'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='teachers.teacherprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='department_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='teachers.department'),
        ),
    ]
