# Generated by Django 5.2.17 on 2026-10-08 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherprofile_max_daily_periods_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_documents', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified / Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_staff_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='background_check_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='contract_signed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('APPLIED', 'Application Received'), ('INTERVIEWED', 'Interviewed'), ('OFFERED', 'Offer Made'), ('ONBOARDING', 'Onboarding & Document Submission'), ('ACTIVE', 'Fully Onboarded & Active'), ('REJECTED', 'Application Rejected')], default='ACTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='document_type',
            field=models.CharField(choices=[('EMPLOYMENT', 'Employment Document'), ('CERTIFICATE', 'Professional Certificate / Degree'), ('CONTRACT', 'Employment Contract'), ('IDENTIFICATION', 'Identification Document (ID/Passport)'), ('RECOMMENDATION', 'Letter of Recommendation'), ('HR_OTHER', 'Other HR Document')], default='EMPLOYMENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teachers.staffprofile'),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
