# Generated by Django 5.2.17 on 2026-08-21 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_section_tutorial_teacher'),
        ('assessments', '0004_studentmark_assessments_school__444765_idx_and_more'),
        ('examinations', '0001_initial'),
        ('tenants', '0002_alter_school_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, default='Read each question carefully before answering. Do not switch tabs or leave fullscreen mode during the test.', null=True)),
                ('start_time', models.DateTimeField(help_text='When students can begin taking the exam')),
                ('end_time', models.DateTimeField(help_text='Deadline when exam closes')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Exam duration in minutes once started')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published / Scheduled'), ('ONGOING', 'Ongoing / Active'), ('COMPLETED', 'Completed / Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('shuffle_questions', models.BooleanField(default=True, help_text='Randomize question order for each student')),
                ('shuffle_options', models.BooleanField(default=True, help_text='Randomize MCQ options order for each student')),
                ('allow_backtracking', models.BooleanField(default=True, help_text='Allow students to navigate back to previous questions')),
                ('show_results_immediately', models.BooleanField(default=False, help_text='Show score immediately after submission')),
                ('show_correct_answers_after_submission', models.BooleanField(default=False, help_text='Allow student to review question solutions after grading')),
                ('enable_proctoring', models.BooleanField(default=True, help_text='Enforce fullscreen and detect tab-switching/blur')),
                ('max_violations_allowed', models.PositiveIntegerField(default=3, help_text='Maximum allowed anti-cheat violations before auto-submit/flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='academics.academicyear')),
                ('assessment_component', models.ForeignKey(blank=True, help_text='Optionally sync scored marks directly to student mark sheet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_exams', to='assessments.assessmentcomponent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_online_exams', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(blank=True, help_text='Optional link to formal scheduled exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_exams', to='examinations.exam')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_exams', to='academics.grade')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_exams', to='academics.academicperiod')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('section', models.ForeignKey(blank=True, help_text='Optional section filter. If null, open to entire grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_exams', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exams', to='academics.subject')),
            ],
            options={
                'ordering': ['-start_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(help_text='The question prompt or description')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice (Single Answer)'), ('MULTIPLE_CHOICE', 'Multiple Answers (Checkboxes)'), ('TRUE_FALSE', 'True / False'), ('SHORT_ANSWER', 'Short Answer (Fill-in)'), ('ESSAY', 'Essay / Long Answer')], default='MCQ', max_length=20)),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown during result review', null=True)),
                ('correct_short_answer', models.CharField(blank=True, help_text='Expected answer for auto-graded fill-in questions', max_length=255, null=True)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('online_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examinations.onlineexam')),
            ],
            options={
                'ordering': ['order', 'question_text'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='examinations.examquestion')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto-Submitted (Time Out / Violation)'), ('GRADED', 'Graded'), ('DISQUALIFIED', 'Disqualified')], default='NOT_STARTED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('extra_time_minutes', models.PositiveIntegerField(default=0)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_passed', models.BooleanField(default=False)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_exam_attempts', to=settings.AUTH_USER_MODEL)),
                ('online_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='examinations.onlineexam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('school', 'online_exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamProctoringLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch Detected'), ('FULLSCREEN_EXIT', 'Fullscreen Exited'), ('RIGHT_CLICK', 'Right Click / Context Menu'), ('COPY_PASTE', 'Copy / Paste Attempt'), ('WINDOW_BLUR', 'Window Blur / Focus Lost'), ('FORCE_SUBMIT', 'Invigilator Force-Submitted'), ('EXTEND_TIME', 'Invigilator Extended Time'), ('DISQUALIFIED', 'Candidate Disqualified')], max_length=30)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_logs', to='examinations.studentexamattempt')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_response', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('teacher_feedback', models.TextField(blank=True, null=True)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='examinations.examquestion')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='student_selections', to='examinations.questionoption')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='examinations.studentexamattempt')),
            ],
            options={
                'unique_together': {('school', 'attempt', 'question')},
            },
        ),
    ]
