# Generated by Django 5.1.15 on 2026-08-11 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('FEDERAL', 'Federal Ministry of Education'), ('REGION', 'Regional Education Bureau'), ('ZONE', 'Zone Education Department'), ('WOREDA', 'Woreda Education Office'), ('SCHOOL', 'School Level')], default='REGION', max_length=20)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='schools.administrativehierarchy')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'unique_together': {('school', 'key')},
            },
        ),
    ]
