# Generated by Django 5.2.17 on 2026-10-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_schoolgallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolnews',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='schoolnews',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Show on the main school landing page'),
        ),
        migrations.AddField(
            model_name='schoolnews',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order sequence (lower values appear first)'),
        ),
    ]
