# Generated by Django 5.1.15 on 2026-08-11 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('REPORT_CARD', 'Report Card'), ('RECEIPT', 'Payment Receipt'), ('TRANSCRIPT', 'Student Transcript'), ('CERTIFICATE', 'Certificate')], max_length=50)),
                ('verification_token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('doc_number', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('REVOKED', 'Revoked')], default='PUBLISHED', max_length=20)),
                ('metadata_json', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='tenants.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionalReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('config_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regional_templates', to='tenants.school')),
            ],
        ),
    ]
