# Generated by Django 5.1.3 on 2026-08-14 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('students', '0002_studentprofile_current_password_display'),
        ('tenants', '0002_alter_school_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTranscriptYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(help_text='e.g. Grade 9, Grade 10', max_length=50)),
                ('grade_level', models.IntegerField(help_text='Numeric level for sorting, e.g. 9, 10')),
                ('academic_year_name', models.CharField(help_text='e.g. 2023/2024', max_length=50)),
                ('subjects_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_transcripts', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_transcripts', to='students.studentprofile')),
            ],
            options={
                'ordering': ['grade_level'],
                'unique_together': {('student', 'grade_level')},
            },
        ),
    ]
